voyages-sncf-technologies/hesperides-gui

.bowerrc, .gitignore, .jshintrc, .travis.yml, app/index.html, bower.json, package.json
This should fix bower problems
=> [MIGRATION] - Some cleaning after github migration

app/application/properties/save-properties-modal.html, app/file/file.js, app/hesperides/hesperides.js, app/properties/properties.js
An auto complete input allow to filter among previous comment (stored on browser local storage)
(fix #4)
=> [Issue#4] Reusing previous comments is now possible

app/hesperides/hesperides.js, app/properties/properties.js
=> [Issue#4] Fixing missing function parameter which led to JS error preventing from saving module properties and diff

app/properties/diff.html, app/properties/properties.js
Replace the mustache instead of overriding the whole valuation
=> [Issue#14] Global properties in diff now works properly (fix #14)

app/properties/iterable-properties-list.html, app/properties/properties.js, app/properties/simple-properties-list.html
Making @required properties required in all situation and fix on no property changed detection.
=> [ISSUE-#21] - Making @required properties required in all situation 

app/application/application.js, app/properties/properties.js, docs/templates.html, docs/valuations.html, pom.xml, test/e2e/diff/diff-modules-spec.js, test/protractor-conf.js
Providing a extra parameter to allow unsecured request, meaning that you won't be notified by error you may encounter. Use carefuly in the right use case. 
fix #25
=> [Issue#25] Notification doesn't show up anymore, the diff works properly

src/app/application/box_renderer.html, src/app/application/change_platform_version.html, src/app/i18n/label_en.json, src/app/i18n/label_fr.json, src/app/properties/properties.js, test/data/data_hesperides.json, test/e2e/logic-representation/logic-representation-spec.js, test/e2e/platforms/platforms-spec.js
[issue#31] Add button Hide/Show in module block display for instances list
=> [Issue/#31] Add button Hide/Show in module block display for instances list

src/app/i18n/label_en.json, src/app/i18n/label_fr.json, src/app/local_changes/localChangesControllers.js
Changing label about detecting local changes within editing module properties
=> [Issue#23] Comments are now send properly as a string instead of object

docs/contribute.html
Demo: https://lucas-c.github.io/hesperides-gui/contribute.html
=> "Contribute" doc update to include backend maven commands

src/app/application/box_properties.html, src/app/application/tree_properties.html, src/app/i18n/label_en.json, src/app/properties/properties.js
Adding context show/hide button to clean useless valuation at instance level, fixing missing translation in english
#42
=> [Issue#42] Updating reference of instance to keep it synchronized and thus to prevent loss of information in futur save

src/app/file/file.js, src/app/local_changes/localChangesControllers.js
=> Fixing United Nation popup issue that prevent us to save a local property valuation when this property is currently empty

src/app/properties/iterable-properties-list.html, src/app/properties/properties-list.html, src/app/properties/properties.js
This will make it possible to sort iterable properties.
=> [issue#19] - Adding the sorting button for iterable properties

src/app/module/module.html, src/app/module/module.js, src/app/shared/list-of-items.html
In module page : 
- Foreach displayed techno, redirection to its page is now available.
- Added a "stopPropagation" to prevent delete button to trigger redirect button
=> [issue#90] Techno redirection in module page

src/app/file/file.js, src/app/module/module.js
According to reviews on pull requests #99 and #100 : 
- Techno page link from module page now opening in a new tab
- Platform files entries array sorting now using lodash library
Closes #90 , and closes #71
Hoping I didn't forget something else ; thanks for being patient
=> [Fix] Small fixes to match general behaviour and syntax

src/app/module/module.js, src/app/template/template.js
When hitting "Save & close" button in template modal, close only if there is no error returned (fixes #76)
Also added a missing "?" before parameters in a techno URL
=> [Issue#76] Save & close only if saved

src/app/properties/properties.js
Change absolute to relative position to extract "name", "version" and "is_working" values
Check non regression with current protractor test
=> [issue#111] Correct init of name, version and is_working_copy

nginx.conf
L'explication : http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
=> Bugfix: Correction de l'urlencoding introduit par nginx

src/app/i18n/label_en.json, src/app/i18n/label_fr.json, src/app/properties/properties.html, src/app/techno/techno-selection.html
La PR https://github.com/voyages-sncf-technologies/hesperides-gui/pull/192 est à merger avant
=> Ajout d'une fenêtre de confirmation de suppression de plateforme - close #190

.eslintrc.json, CHANGELOG.md, package-lock.json, package.json, src/app/datepicker/datepicker.js, src/app/event/event.js, src/app/hesperides/hesperides.js, src/app/index.html, src/app/menu/menu.js, src/app/properties/platform-menu-modal-from.html, src/app/properties/platform-menu-modal.html, src/app/properties/properties.html, src/app/properties/properties.js, src/app/user/user.js
\+ suppression de l'état partagé Angular "session"
\+ ajout d'un cache sur UserService.authenticate
\+ suppression des polyfills sur les classes natives Regex & String
=> Fix: il désormais à nouveau possible de flaguer une plateforme comme "de production" - close #203

CHANGELOG.md, src/app/module/module.js, src/app/properties/properties.js
\+ remplacement de l'appel à modules/search, plus pertinent fonctionnelement & en termes de perfs
=> Fix: le tooltip était manquant pour les propriétés sans valorisation

package.json, src/app/diff/diff.js, src/app/diff/global_properties_diff_wizard.html, src/app/diff/properties_diff_wizard.html, src/app/hesperides/hesperides.js, src/app/properties/box_properties.html, src/app/properties/properties.html, src/app/properties/tree_properties.html, tech_docs/tests.md, test/e2e/diff/diff-platforms-spec.js, test/e2e/utils.js
Je me suis permis de mettre le formulaire de restauration de plateforme en commentaire après avoir entendu de plusieurs intégrateurs (dont Jordan et Gildas) que cette fonctionnalité, comme la suppression de plateforme, a plus de sens à n'être que dans le Swagger. Selon eux, les utilisateurs lambda n'en ont pas besoin et les autres, ceux qui en ont besoin, sauront utiliser le Swagger.
Si tu veux que je décommente ou que je supprime le code associé à ce formulaire, dis-le moi :)
=> Fix #244 Correction du diff de propriétés globales avec timestamp

.travis.yml, CHANGELOG.md, docs/glossary.html, src/app/i18n/label_en.json, src/app/i18n/label_fr.json, src/app/properties/box_renderer.html, src/app/properties/properties.html, src/app/properties/properties.js
=> Add: warning affiché pour les plateformes non identifiées comme de production mais dont le nom débute par PRD ou PROD - close #255

src/app/diff/diff.css, src/app/diff/diff.html, src/app/diff/diff.js, src/app/diff/properties_diff_wizard.html, test/e2e/diff/diff-platforms-spec.js
\+ Sauvegarde des propriétés itérables lors du report de propriétés
=> Fix #281 Bug d'affichage du diff

CHANGELOG.md, src/app/properties/change_module_version.html
Will close https://github.com/voyages-sncf-technologies/hesperides/issues/747
=> Fix: sticky default input value in change_module_version modal

.eslintrc.json, .gitignore, .travis.yml, CHANGELOG.md, package-lock.json, package.json, src/app/application/instance_properties.html, src/app/properties/properties.js, src/app/properties/simple-properties-list.html, tech_docs/tests.md, test/e2e/.eslintrc.json, test/e2e/config.json, test/e2e/features/modules/create-modules.feature, test/e2e/logic-representation/logic-representation-spec.js, test/e2e/modules/modules-spec.js, test/e2e/properties/iterable-properties-spec.js, test/e2e/properties/properties-spec.js, test/e2e/protractor-bdd.js, test/e2e/protractor-conf.js, test/e2e/stepDefinitions/hooks.js, test/e2e/stepDefinitions/modules/create-modules.steps.js
Aperçu du rendu des tooltips :
=> Add: tooltip indiquant lorsque des propriétés globales sont employées pour valoriser des propriétés - close #254

src/app/application/application.js, src/app/application/properties_globales.html, src/app/properties/properties.js, src/app/properties/tree_properties.html
_cf._ https://github.com/voyages-sncf-technologies/hesperides-gui/issues/321
=> Code cleanup: supprimer refreshGlobalPropertiesData dans properties.js - close #321

.pre-commit-config.yaml, CHANGELOG.md, list_unused_i18n.py
Ce script est issu d'un autre projet AngularJS sur lequel j'ai bossé.
En relisant https://github.com/voyages-sncf-technologies/hesperides-gui/pull/406 je me suis dis qu'il pourrait être utile de l'introduire dans ce repo.
Résultat d'exécution sur le code actuel :
```
No usage found for message.techno.delete.confirm
No usage found for settings.display
No usage found for detailed.properties.column.name
No usage found for properties.compare.hideDeletedProperties.disabled.tooltip
No usage found for module.template.event.error
No usage found for module.event.updated.details
No usage found for techno.all.title
No usage found for properties.instance.show.all
No usage found for properties.boxMode.title
No usage found for properties.instance.hide.all
No usage found for …
```
=> Ajout de list_unused_i18n.py

.travis.yml, .travis/run_bdd_test.sh, package-lock.json, src/app/properties/simple-properties-list.html, test/bdd/features/platforms/save-module-properties.feature, test/bdd/glue/helpers/assert.js, test/bdd/glue/hooks.js, test/bdd/glue/scenarios/platforms/module-properties-list.js, test/bdd/glue/scenarios/platforms/save-module-properties.js
The following backend error message is still displayed:
=> Fix: Suppression du controle de surface sur les propriétés requises - close #334 & #417
